# -*- coding: utf-8 -*-
"""crawl.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GpPiuuopbcdJAYMHCT13r7N-X0LEN9Fy
"""

import requests
from bs4 import BeautifulSoup
import datetime

def crawl_gold_prices():
    url = 'https://sjc.com.vn/'

    # Gửi yêu cầu GET đến trang web
    response = requests.get(url)

    # Kiểm tra nếu yêu cầu thành công
    if response.status_code == 200:
        soup = BeautifulSoup(response.text, 'html.parser')

        # Tìm kiếm các thông tin cần thiết trong HTML
        prices_info = {}

        # Cần chỉ định chính xác class hoặc id chứa giá để lấy dữ liệu
        # Ví dụ: giả sử bạn tìm thấy chúng trong một bảng với class là 'table-gia'
        table = soup.find('table', {'class': 'table-gia'})  # Cập nhật đúng class/id ở đây

        if table:
            rows = table.find_all('tr')
            for row in rows[1:]:  # Bỏ qua hàng đầu tiên nếu nó là tiêu đề
                columns = row.find_all('td')
                if len(columns) >= 3:  # Đảm bảo có đủ cột dữ liệu
                    location = columns[0].text.strip()  # Nơi giao dịch
                    buy_price = columns[1].text.strip()  # Giá mua vào
                    sell_price = columns[2].text.strip()  # Giá bán ra

                    # Lưu trữ thông tin
                    prices_info[location] = {
                        'timestamp': datetime.datetime.now(),
                        'buy_price': buy_price,
                        'sell_price': sell_price
                    }

            return prices_info
        else:
            print("Không tìm thấy bảng giá.")
            return None
    else:
        print(f"Crawl không thành công với mã trạng thái: {response.status_code}")
        return None

# Chạy hàm crawl
gold_prices = crawl_gold_prices()
if gold_prices:
    for location, price_info in gold_prices.items():
        print(f"Nơi giao dịch: {location}, Giá mua vào: {price_info['buy_price']}, Giá bán ra: {price_info['sell_price']}, Thời gian: {price_info['timestamp']}")