# -*- coding: utf-8 -*-
"""transform.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17q6rMf0C5LdlgHi_UNfHI4W9pz3QEQ-c
"""

from bs4 import BeautifulSoup

def clean_html(raw_html):
    """
    Hàm để làm sạch dữ liệu HTML và trả về văn bản đã được làm sạch.
    :param raw_html: Chuỗi chứa mã HTML cần được làm sạch
    :return: Chuỗi văn bản đã làm sạch
    """
    soup = BeautifulSoup(raw_html, 'html.parser')
    # Lấy ra văn bản từ các thẻ HTML
    clean_text = soup.get_text(separator=' ', strip=True)
    return clean_text

# Ví dụ sử dụng
if __name__ == '__main__':
    raw_data = """
    <div>
        <h1>Giá vàng SJC</h1>
        <p>Giá mua vào: <strong>60.000.000 VND</strong></p>
        <p>Giá bán ra: <strong>61.000.000 VND</strong></p>
    </div>
    """

    cleaned_data = clean_html(raw_data)
    print(cleaned_data)